#!/usr/bin/env node
/**
 * Build (and optionally post) a PR comment embedding the GIF for every
 * shot-scraper storyboard a plugin ships.
 *
 * Usage:
 *   node comment-demos.mjs <plugin-id>            # print Markdown
 *   node comment-demos.mjs <plugin-id> --pr 2     # post/update PR comment with gh
 *   DEMO_BASE_URL=https://... node comment-demos.mjs <plugin-id>
 */

import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const DEMO_TOOLS_DIR = dirname(fileURLToPath(import.meta.url))
const PLUGINS_DIR = resolve(DEMO_TOOLS_DIR, '..')
const REPO_ROOT = resolve(DEMO_TOOLS_DIR, '../../../../..')

function git(args) {
  const result = spawnSync('git', args, { cwd: REPO_ROOT, encoding: 'utf8' })
  if (result.status !== 0) return ''
  return result.stdout.trim()
}

function repoSlug() {
  if (process.env.GITHUB_REPOSITORY) return process.env.GITHUB_REPOSITORY
  const url = git(['config', '--get', 'remote.origin.url'])
  const match = url.match(/github\.com[:/](.+?)(?:\.git)?$/)
  return match?.[1] ?? 'OWNER/REPO'
}

function branchName() {
  return process.env.GITHUB_HEAD_REF || process.env.GITHUB_REF_NAME || git(['rev-parse', '--abbrev-ref', 'HEAD'])
}

function outputFor(storyboardPath, pluginDemoDir) {
  const text = readFileSync(storyboardPath, 'utf8')
  const match = text.match(/^output:\s*(.+)$/m)
  if (!match) throw new Error(`Storyboard has no output: ${storyboardPath}`)
  const raw = match[1].trim().replace(/^['"]|['"]$/g, '')
  return resolve(pluginDemoDir, raw)
}

function demoTitle(storyboardName) {
  return storyboardName
    .replace(/\.(ya?ml)$/i, '')
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

/**
 * Human-viewable page for a committed file (the blob viewer). Used for the
 * text links so clicking lands on the file page, not a raw byte stream.
 */
function blobUrlFor(path) {
  const rel = relative(REPO_ROOT, path).replaceAll('\\', '/')
  if (process.env.DEMO_BASE_URL) return `${process.env.DEMO_BASE_URL.replace(/\/$/, '')}/${rel}`
  return `https://github.com/${repoSlug()}/blob/${branchName()}/${rel}`
}

/**
 * Image src for embedding a committed file in a PR/issue body.
 *
 * Uses the `github.com/.../blob/<ref>/<path>?raw=true` form, NOT
 * `raw.githubusercontent.com`: on a PRIVATE repo the latter needs a
 * short-lived `?token=` that GitHub's image proxy (camo) can't supply, so the
 * image renders broken and clicking it bounces to a github.com sign-in. The
 * github.com blob URL is same-origin and served to viewers who can already
 * see the PR. With DEMO_BASE_URL set (custom public host) the file is served
 * directly, so no `?raw=true` is appended.
 */
function imageUrlFor(path) {
  if (process.env.DEMO_BASE_URL) return blobUrlFor(path)
  return `${blobUrlFor(path)}?raw=true`
}

function buildBody(pluginId) {
  const pluginDemoDir = join(PLUGINS_DIR, pluginId, 'demo')
  const storyboardDir = join(pluginDemoDir, 'storyboards')
  if (!existsSync(storyboardDir)) {
    throw new Error(`No storyboards found for plugin '${pluginId}' (expected ${storyboardDir})`)
  }
  const storyboards = readdirSync(storyboardDir)
    .filter((name) => name.endsWith('.yml') || name.endsWith('.yaml'))
    .sort()

  const relDemoDir = relative(REPO_ROOT, pluginDemoDir).replaceAll('\\', '/')
  const sections = storyboards.map((name) => {
    const output = outputFor(join(storyboardDir, name), pluginDemoDir)
    const gif = output.replace(/\.webm$/i, '.gif')
    const relGif = relative(REPO_ROOT, gif).replaceAll('\\', '/')
    const missing = existsSync(gif) ? '' : `\n\n> ⚠️ Expected GIF not found at \`${relGif}\`. Run \`node apps/electron/src/plugins/demo/record.mjs ${pluginId}\`.\n`
    return [
      `### ${demoTitle(name)}`,
      '',
      `[Storyboard](${blobUrlFor(join(storyboardDir, name))}) · [GIF source](${blobUrlFor(gif)})`,
      '',
      `![${demoTitle(name)}](${imageUrlFor(gif)})`,
      missing,
    ].join('\n')
  })

  return [
    `<!-- plugin-demo-comment:${pluginId} -->`,
    `## \`${pluginId}\` product demos`,
    '',
    `Generated from the shot-scraper storyboards in \`${relDemoDir}/storyboards/\`.`,
    '',
    ...sections,
    '',
    '_Generated by `apps/electron/src/plugins/demo/comment-demos.mjs`._',
  ].join('\n')
}

function postToPr(pluginId, prNumber, body) {
  const marker = `<!-- plugin-demo-comment:${pluginId} -->`
  const bodyPath = join(DEMO_TOOLS_DIR, '.demo-comment.md')
  writeFileSync(bodyPath, body)

  const comments = spawnSync('gh', [
    'api',
    `repos/${repoSlug()}/issues/${prNumber}/comments`,
    '--paginate',
    '--jq',
    `.[] | select(.body | contains("${marker}")) | .id`,
  ], { cwd: REPO_ROOT, encoding: 'utf8' })

  if (comments.status !== 0) {
    throw new Error(comments.stderr || 'failed to list PR comments')
  }

  const id = comments.stdout.trim().split('\n').filter(Boolean).at(-1)
  const args = id
    ? ['api', `repos/${repoSlug()}/issues/comments/${id}`, '-X', 'PATCH', '-f', `body=@${bodyPath}`]
    : ['pr', 'comment', String(prNumber), '--body-file', bodyPath]
  const result = spawnSync('gh', args, { cwd: REPO_ROOT, stdio: 'inherit' })
  if (result.status !== 0) throw new Error(`gh ${args.join(' ')} failed`)
}

const positional = process.argv.slice(2).filter((arg, i, all) => !arg.startsWith('-') && all[i - 1] !== '--pr')
const pluginId = positional[0]
if (!pluginId) {
  throw new Error('Usage: node comment-demos.mjs <plugin-id> [--pr <number>]')
}
const prFlag = process.argv.indexOf('--pr')
const prNumber = prFlag === -1 ? null : process.argv[prFlag + 1]
const body = buildBody(pluginId)

if (prNumber) {
  postToPr(pluginId, prNumber, body)
} else {
  process.stdout.write(`${body}\n`)
}
